---
deployment:
  tasks:
    # - sh ~/public_html/aa-client/deploy1.sh 2>&1
    - export DEPLOYPATH=~/public_html/
    - /bin/cp -R ~/repositories/aa-client/ $DEPLOYPATH
    - sh ~/public_html/aa-client/deploy.sh 2>&1
    